package pl.groo.Helper;

import java.util.HashMap;

// Class just for the first database initialization. I had this list in one of my early projects
public class DBHelper {



    public static HashMap<Integer,String> GetBank (){
        HashMap<Integer,String> NRBMap = new HashMap<Integer, String>();
        NRBMap.put(1010,"Narodowy Bank Polski");
        NRBMap.put(1010,"Narodowy Bank Polski");
        NRBMap.put(1020,"Powszechna Kasa Oszczędności Bank Polski SA");
        NRBMap.put(1030,"Bank Handlowy w Warszawie SA");
        NRBMap.put(1050,"ING Bank Śląski SA");
        NRBMap.put(1060,"Bank BPH SA");
        NRBMap.put(1090,"Bank Zachodni WBK SA");
        NRBMap.put(1130,"Bank Gospodarstwa Krajowego");
        NRBMap.put(1140,"mBank SA");
        NRBMap.put(1160,"Bank Millennium SA");
        NRBMap.put(1220,"Bank Handlowo-Kredytowy Spółka Akcyjna w Katowicach w likwidacji");
        NRBMap.put(1240,"Bank Polska Kasa Opieki SA");
        NRBMap.put(1280,"HSBC Bank Polska SA");
        NRBMap.put(1320,"Bank Pocztowy SA");
        NRBMap.put(1470,"Euro Bank SA");
        NRBMap.put(1540,"Bank Ochrony Środowiska SA");
        NRBMap.put(1580,"Mercedes-Benz Bank Polska SA");
        NRBMap.put(1610,"SGB-Bank SA");
        NRBMap.put(1670,"RBS Bank (Polska) SA");
        NRBMap.put(1680,"PLUS BANK SA");
        NRBMap.put(1750,"Raiffeisen Bank Polska SA");
        NRBMap.put(1840,"Societe Generale SA Oddział w Polsce");
        NRBMap.put(1870,"Nest Bank S.A.");
        NRBMap.put(1890,"Pekao Bank Hipoteczny SA");
        NRBMap.put(1910,"Deutsche Bank Polska SA");
        NRBMap.put(1930,"BANK POLSKIEJ SPÓŁDZIELCZOŚCI SA");
        NRBMap.put(1940,"Credit Agricole Bank Polska SA");
        NRBMap.put(1950,"Idea Bank SA");
        NRBMap.put(2030,"Bank BGŻ BNP Paribas SA");
        NRBMap.put(2120,"Santander Consumer Bank SA");
        NRBMap.put(2130,"VOLKSWAGEN BANK POLSKA SA");
        NRBMap.put(2140,"FCA-Group Bank Polska SA");
        NRBMap.put(2150,"mBank Hipoteczny SA");
        NRBMap.put(2160,"Toyota Bank Polska SA");
        NRBMap.put(2190,"DNB Bank Polska SA");
        NRBMap.put(2240,"Banque PSA Finance SA Oddział w Polsce");
        NRBMap.put(2250,"Svenska Handelsbanken AB SA Oddział w Polsce");
        NRBMap.put(2290,"BPI Bank Polskich Inwestycji SA");
        NRBMap.put(2320,"Nykredit Realkredit A/S SA - Oddział w Polsce");
        NRBMap.put(2350,"BNP PARIBAS SA Oddział w Polsce");
        NRBMap.put(2360,"Danske Bank A/S SA Oddział w Polsce");
        NRBMap.put(2370,"Skandinaviska Enskilda Banken AB (SA) - Oddział w Polsce");
        NRBMap.put(2390,"CAIXABANK, S.A. (SPÓŁKA AKCYJNA)ODDZIAŁ W POLSCE");
        NRBMap.put(2410,"Elavon Financial Services Designated Activity Company (spółka z o.o. o wyznaczonym przedmiocie działalności) Oddział w Polsce");
        NRBMap.put(2430,"BNP Paribas Securities Services SKA Oddział w Polsce");
        NRBMap.put(2450,"HSBC Bank plc (Spółka Akcyjna) Oddział w Polsce");
        NRBMap.put(2470,"HAITONG BANK, S.A. Spółka Akcyjna Oddział w Polsce");
        NRBMap.put(2480,"Getin Noble Bank SA");
        NRBMap.put(2490,"Alior Bank SA");
        NRBMap.put(2510,"Aareal Bank Aktiengesellschaft (Spółka Akcyjna) - Oddział w Polsce");
        NRBMap.put(2540,"Citibank Europe plc (Publiczna Spółka Akcyjna) Oddział w Polsce");
        NRBMap.put(2550,"Ikano Bank AB (publ) Spółka Akcyjna Oddział w Polsce");
        NRBMap.put(2560,"Nordea Bank AB SA Oddział w Polsce");
        NRBMap.put(2570,"UBS Limited (spółka z ograniczoną odpowiedzialnością) Oddział w Polsce");
        NRBMap.put(2580,"J.P. Morgan Europe Limited Sp. z o.o. Oddział w Polsce");
        NRBMap.put(2600,"Bank of China (Luxembourg) S.A. Spółka Akcyjna Oddział w Polsce");
        NRBMap.put(2620,"Industrial and Commercial Bank of China (Europe) S.A. (Spółka Akcyjna) Oddział w Polsce");
        NRBMap.put(2640,"RCI Banque Spółka Akcyjna Oddział w Polsce");
        NRBMap.put(2650,"EUROCLEAR Bank SA/NV (Spółka Akcyjna) - Oddział w Polsce");
        NRBMap.put(2660,"Intesa Sanpaolo S.p.A. Spółka Akcyjna Oddział w Polsce");
        NRBMap.put(2670,"Western Union International Bank GmbH, Sp. z o.o. Oddział w Polsce");
        NRBMap.put(2690,"PKO Bank Hipoteczny SA");
        NRBMap.put(2700,"TF BANK AB (Spółka z ograniczoną odpowiedzialnością) Oddział w Polsce");
        NRBMap.put(2710,"FCE Bank Spółka Akcyjna Oddział w Polsce");
        NRBMap.put(2720,"AS Inbank Spółka Akcyjna - Oddział w Polsce");
        NRBMap.put(2730,"China Construction Bank (Europe) S.A. (Spółka Akcyjna) Oddział w Polsce");
        NRBMap.put(2740,"MUFG Bank (Europe) N.V. S.A. Oddział w Polsce");
        NRBMap.put(2750,"John Deere Bank S.A. Spółka Akcyjna Oddział w Polsce");
        NRBMap.put(8001, "Bank Spółdzielczy w Otwocku");
        NRBMap.put(8002, "Bank Spółdzielczy w Piasecznie");
        NRBMap.put(8003, "Mazovia Bank Spółdzielczy");
        NRBMap.put(8004, "Bank Spółdzielczy w Raszynie");
        NRBMap.put(8006, "Spółdzielczy Bank Rzemiosła i Rolnictwa w Wołominie w upadłości likwidacyjnej");
        NRBMap.put(8008, "Bank Spółdzielczy w Tarczynie");
        NRBMap.put(8009, "Mazowiecki Bank Spółdzielczy w Łomiankach");
        NRBMap.put(8011, "Bank Spółdzielczy w Nowym Dworze Mazowieckim");
        NRBMap.put(8013, "Bank Spółdzielczy w Legionowie");
        NRBMap.put(8015, "Warszawski Bank Spółdzielczy");
        NRBMap.put(8017, "Bank Spółdzielczy w Nadarzynie w upadłości");
        NRBMap.put(8019, "Bank Spółdzielczy w Halinowie");
        NRBMap.put(8023, "Bank Spółdzielczy w Karczewie");
        NRBMap.put(8025, "Bank Spółdzielczy w Białej Podlaskiej");
        NRBMap.put(8034, "Bank Spółdzielczy w Konstantynowie");
        NRBMap.put(8035, "Bank Spółdzielczy w Kornicy");
        NRBMap.put(8037, "Bank Spółdzielczy w Łomazach");
        NRBMap.put(8038, "Bank Spółdzielczy w Łosicach");
        NRBMap.put(8039, "Bank Spółdzielczy w Międzyrzecu Podlaskim");
        NRBMap.put(8042, "Bank Spółdzielczy w Parczewie");
        NRBMap.put(8044, "Bank Spółdzielczy w Platerowie");
        NRBMap.put(8046, "Bank Spółdzielczy w Radzyniu Podlaskim");
        NRBMap.put(8055, "Bank Spółdzielczy w Wisznicach");
        NRBMap.put(8060, "Bank Spółdzielczy w Białymstoku");
        NRBMap.put(8061, "Bank Spółdzielczy w Bielsku Podlaskim");
        NRBMap.put(8063, "Bank Spółdzielczy w Brańsku");
        NRBMap.put(8071, "Bank Spółdzielczy w Hajnówce");
        NRBMap.put(8074, "Bank Spółdzielczy w Juchnowcu Górnym");
        NRBMap.put(8076, "Podlaski Bank Spółdzielczy w Knyszynie");
        NRBMap.put(8077, "Bank Spółdzielczy w Korycinie");
        NRBMap.put(8081, "Bank Spółdzielczy w Łapach");
        NRBMap.put(8085, "Bank Spółdzielczy w Mońkach");
        NRBMap.put(8086, "Bank Spółdzielczy w Narwi");
        NRBMap.put(8092, "Bank Spółdzielczy w Siemiatyczach");
        NRBMap.put(8093, "Bank Spółdzielczy w Sokółce");
        NRBMap.put(8094, "Bank Spółdzielczy w Suchowoli");
        NRBMap.put(8099, "Podlasko-Mazurski Bank Spółdzielczy w Zabłudowie");
        NRBMap.put(8110, "ABS Bank Spółdzielczy");
        NRBMap.put(8111, "Beskidzki Bank Spółdzielczy");
        NRBMap.put(8112, "Bank Spółdzielczy w Brzeźnicy");
        NRBMap.put(8113, "Bank Spółdzielczy w Cieszynie");
        NRBMap.put(8117, "Bank Spółdzielczy w Jasienicy");
        NRBMap.put(8118, "Bank Spółdzielczy w Jeleśni");
        NRBMap.put(8119, "Bank Spółdzielczy w Kalwarii Zebrzydowskiej");
        NRBMap.put(8120, "Bank Spółdzielczy w Kętach");
        NRBMap.put(8124, "Bank Spółdzielczy w Porąbce");
        NRBMap.put(8125, "Bank Spółdzielczy w Rajczy");
        NRBMap.put(8126, "Bank Spółdzielczy w Skoczowie");
        NRBMap.put(8128, "Bank Spółdzielczy w Suchej Beskidzkiej");
        NRBMap.put(8129, "Bank Spółdzielczy w Ustroniu");
        NRBMap.put(8131, "Bank Spółdzielczy w Węgierskiej Górce");
        NRBMap.put(8133, "Bank Spółdzielczy w Bystrej");
        NRBMap.put(8134, "Bank Spółdzielczy w Wilamowicach");
        NRBMap.put(8136, "Bank Spółdzielczy w Zatorze");
        NRBMap.put(8137, "Bank Spółdzielczy w Żywcu");
        NRBMap.put(8140, "ETNO Bank Spółdzielczy");
        NRBMap.put(8141, "Bank Spółdzielczy w Gilowicach");
        NRBMap.put(8142, "Bank Spółdzielczy w Bydgoszczy");
        NRBMap.put(8143, "Bank Spółdzielczy Solec Kujawski");
        NRBMap.put(8144, "Bank Spółdzielczy w Koronowie");
        NRBMap.put(8146, "Bank Spółdzielczy w Chojnicach");
        NRBMap.put(8147, "Bank Spółdzielczy w Czersku");
        NRBMap.put(8149, "Bank Spółdzielczy w Inowrocławiu");
        NRBMap.put(8151, "Bank Spółdzielczy w Kruszwicy");
        NRBMap.put(8159, "Bank Spółdzielczy w Strzelnie");
        NRBMap.put(8162, "Bank Spółdzielczy w Więcborku");
        NRBMap.put(8164, "Bank Spółdzielczy w Szubinie");
        NRBMap.put(8166, "Bank Spółdzielczy w Kcyni");
        NRBMap.put(8167, "Bank Spółdzielczy w Barcinie");
        NRBMap.put(8168, "Bank Spółdzielczy w Świeciu");
        NRBMap.put(8169, "Bank Spółdzielczy w Osiu");
        NRBMap.put(8170, "Bank Spółdzielczy w Pruszczu Pomorskim");
        NRBMap.put(8173, "Bank Spółdzielczy w Nowem n/Wisłą");
        NRBMap.put(8174, "Bank Spółdzielczy w Tucholi");
        NRBMap.put(8179, "Bank Spółdzielczy w Nakle n/Notecią");
        NRBMap.put(8181, "Bank Spółdzielczy \"Pałuki\" w Żninie");
        NRBMap.put(8185, "Piastowski Bank Spółdzielczy w Janikowie");
        NRBMap.put(8187, "Wschodni Bank Spółdzielczy w Chełmie");
        NRBMap.put(8188, "Bank Spółdzielczy w Wojsławicach");
        NRBMap.put(8191, "Bank Spółdzielczy w Cycowie");
        NRBMap.put(8192, "Bank Spółdzielczy w Sawinie");
        NRBMap.put(8195, "Bank Spółdzielczy w Leśniowicach");
        NRBMap.put(8200, "Bank Spółdzielczy w Krasnymstawie");
        NRBMap.put(8202, "Bank Spółdzielczy w Białopolu");
        NRBMap.put(8212, "Bank Spółdzielczy w Bieżuniu");
        NRBMap.put(8213, "Polski Bank Spółdzielczy w Ciechanowie");
        NRBMap.put(8215, "Bank Spółdzielczy w Działdowie z siedzibą w Lidzbarku");
        NRBMap.put(8220, "Bank Spółdzielczy w Grudusku");
        NRBMap.put(8225, "Bank Spółdzielczy w Mławie");
        NRBMap.put(8226, "Bank Spółdzielczy w Nasielsku");
        NRBMap.put(8229, "Bank Spółdzielczy w Glinojecku");
        NRBMap.put(8230, "Bank Spółdzielczy w Płońsku");
        NRBMap.put(8232, "Bank Spółdzielczy w Pułtusku");
        NRBMap.put(8233, "Bank Spółdzielczy w Raciążu");
        NRBMap.put(8238, "Bank Spółdzielczy w Strzegowie");
        NRBMap.put(8241, "Bank Spółdzielczy w Załuskach");
        NRBMap.put(8242, "Bank Spółdzielczy w Żurominie");
        NRBMap.put(8248, "Bank Spółdzielczy w Kłobucku");
        NRBMap.put(8249, "Bank Spółdzielczy we Wręczycy Wielkiej");
        NRBMap.put(8250, "Bank Spółdzielczy w Krzepicach");
        NRBMap.put(8256, "Bank Spółdzielczy we Mstowie");
        NRBMap.put(8258, "Bank Spółdzielczy w Mykanowie");
        NRBMap.put(8259, "Bank Spółdzielczy w Popowie z/s w Zawadach");
        NRBMap.put(8260, "Bank Spółdzielczy w Poczesnej");
        NRBMap.put(8264, "Bank Spółdzielczy w Kłomnicach");
        NRBMap.put(8265, "Bank Spółdzielczy w Pajęcznie");
        NRBMap.put(8267, "Bank Spółdzielczy w Żytnie");
        NRBMap.put(8273, "Bank Spółdzielczy w Konopiskach");
        NRBMap.put(8276, "Bank Spółdzielczy w Koniecpolu");
        NRBMap.put(8277, "Bank Spółdzielczy w Szczekocinach");
        NRBMap.put(8279, "Międzypowiatowy Bank Spółdzielczy w Myszkowie");
        NRBMap.put(8288, "Bank Spółdzielczy w Koszęcinie");
        NRBMap.put(8300, "Powiślański Bank Spółdzielczy w Kwidzynie");
        NRBMap.put(8303, "Bank Spółdzielczy w Malborku");
        NRBMap.put(8304, "Bank Spółdzielczy w Nowym Stawie");
        NRBMap.put(8306, "Żuławski Bank Spółdzielczy");
        NRBMap.put(8308, "Bank Spółdzielczy w Stegnie");
        NRBMap.put(8309, "Bank Spółdzielczy w Sztumie");
        NRBMap.put(8310, "Bank Spółdzielczy w Dzierzgoniu");
        NRBMap.put(8313, "Braniewsko - Pasłęcki Bank Spółdzielczy z siedzibą w Pasłęku");
        NRBMap.put(8316, "Bank Spółdzielczy w Ornecie");
        NRBMap.put(8317, "Bank Spółdzielczy Pieniężno");
        NRBMap.put(8319, "Bank Spółdzielczy w Prabutach");
        NRBMap.put(8320, "Bank Spółdzielczy w Suszu");
        NRBMap.put(8324, "Bank Spółdzielczy w Sierakowicach");
        NRBMap.put(8328, "Bank Spółdzielczy w Kościerzynie");
        NRBMap.put(8335, "Bank Spółdzielczy w Pruszczu Gdańskim");
        NRBMap.put(8337, "Bank Spółdzielczy w Pszczółkach");
        NRBMap.put(8340, "Bank Spółdzielczy w Starogardzie Gdańskim");
        NRBMap.put(8341, "Bank Spółdzielczy w Lubichowie");
        NRBMap.put(8342, "Bank Spółdzielczy w Skórczu");
        NRBMap.put(8343, "Bank Spółdzielczy w Smętowie Granicznym");
        NRBMap.put(8345, "Bank Spółdzielczy w Tczewie");
        NRBMap.put(8346, "Bank Spółdzielczy w Gniewie");
        NRBMap.put(8348, "Bank Spółdzielczy w Pucku");
        NRBMap.put(8349, "Bank Spółdzielczy w Krokowej");
        NRBMap.put(8350, "Kaszubski Bank Spółdzielczy w Wejherowie");
        NRBMap.put(8351, "Bank Rumia Spółdzielczy");
        NRBMap.put(8355, "Gospodarczy Bank Spółdzielczy w Barlinku");
        NRBMap.put(8359, "Zachodniopomorski Bank Spółdzielczy");
        NRBMap.put(8362, "Lubusko-Wielkopolski Bank Spółdzielczy z siedzibą w Drezdenku");
        NRBMap.put(8363, "Gospodarczy Bank Spółdzielczy w Gorzowie Wielkopolskim");
        NRBMap.put(8367, "Gospodarczy Bank Spółdzielczy Międzyrzecz");
        NRBMap.put(8369, "Bank Spółdzielczy w Ośnie Lubuskim");
        NRBMap.put(8371, "Bank Spółdzielczy w Rzepinie");
        NRBMap.put(8372, "Bank Spółdzielczy w Santoku");
        NRBMap.put(8382, "Bank Spółdzielczy w Pieńsku");
        NRBMap.put(8384, "Bank Spółdzielczy Lwówek Śląski w Lwówku Śląskim");
        NRBMap.put(8392, "Łużycki Bank Spółdzielczy w Lubaniu");
        NRBMap.put(8395, "Bank Spółdzielczy w Kamiennej Górze");
        NRBMap.put(8404, "Bank Spółdzielczy Ziemi Kaliskiej");
        NRBMap.put(8407, "Bank Spółdzielczy w Pleszewie");
        NRBMap.put(8409, "Bank Spółdzielczy w Dobrzycy");
        NRBMap.put(8410, "Bank Spółdzielczy w Krotoszynie");
        NRBMap.put(8413, "Spółdzielczy Bank Ludowy w Kępnie");
        NRBMap.put(8426, "Bank Spółdzielczy w Żerkowie");
        NRBMap.put(8427, "Bank Spółdzielczy w Jarocinie");
        NRBMap.put(8430, "Bank Spółdzielczy w Raszkowie");
        NRBMap.put(8431, "Spółdzielczy Bank Ludowy w Skalmierzycach");
        NRBMap.put(8435, "Bank Spółdzielczy w Tychach");
        NRBMap.put(8436, "Mikołowski Bank Spółdzielczy w Mikołowie");
        NRBMap.put(8437, "Śląski Bank Spółdzielczy \"Silesia\" w Katowicach");
        NRBMap.put(8438, "Bank Spółdzielczy w Będzinie");
        NRBMap.put(8441, "Bank Spółdzielczy w Siewierzu");
        NRBMap.put(8444, "Bank Spółdzielczy w Chrzanowie");
        NRBMap.put(8445, "Bank Spółdzielczy w Jaworznie");
        NRBMap.put(8446, "Bank Spółdzielczy w Miedźnej");
        NRBMap.put(8447, "Bank Spółdzielczy w Pawłowicach");
        NRBMap.put(8448, "Bank Spółdzielczy w Pszczynie");
        NRBMap.put(8449, "Bank Spółdzielczy w Olkuszu w likwidacji");
        NRBMap.put(8450, "Bank Spółdzielczy w Wolbromiu");
        NRBMap.put(8453, "Bank Spółdzielczy Czechowice-Dziedzice-Bestwina");
        NRBMap.put(8454, "Orzesko-Knurowski Bank Spółdzielczy z siedzibą w Knurowie");
        NRBMap.put(8455, "Rybnicki Bank Spółdzielczy");
        NRBMap.put(8456, "Bank Spółdzielczy w Żorach");
        NRBMap.put(8457, "Bank Spółdzielczy w Gliwicach");
        NRBMap.put(8460, "Bank Spółdzielczy w Sośnicowicach");
        NRBMap.put(8463, "Bank Spółdzielczy w Tarnowskich Górach");
        NRBMap.put(8466, "Bank Spółdzielczy w Tworogu");
        NRBMap.put(8467, "Bank Spółdzielczy w Świerklańcu");
        NRBMap.put(8468, "Bank Spółdzielczy w Wodzisławiu Śląskim");
        NRBMap.put(8469, "Bank Spółdzielczy w Gorzycach");
        NRBMap.put(8470, "Bank Spółdzielczy w Jastrzębiu Zdroju");
        NRBMap.put(8471, "Bank Spółdzielczy Bytom");
        NRBMap.put(8474, "Bank Spółdzielczy w Krzyżanowicach");
        NRBMap.put(8475, "Bank Spółdzielczy w Raciborzu");
        NRBMap.put(8480, "Bank Spółdzielczy w Busku-Zdroju");
        NRBMap.put(8483, "Bank Spółdzielczy w Chmielniku");
        NRBMap.put(8485, "Bank Spółdzielczy Daleszyce-Górno");
        NRBMap.put(8490, "Bank Spółdzielczy w Jędrzejowie");
        NRBMap.put(8493, "Bank Spółdzielczy w Kielcach");
        NRBMap.put(8494, "Bank Spółdzielczy w Końskich");
        NRBMap.put(8499, "Bank Spółdzielczy w Łopusznie");
        NRBMap.put(8507, "Bank Spółdzielczy w Ostrowcu Świętokrzyskim");
        NRBMap.put(8509, "Bank Spółdzielczy w Pińczowie");
        NRBMap.put(8512, "Bank Spółdzielczy w Samsonowie");
        NRBMap.put(8513, "Bank Spółdzielczy w Sędziszowie");
        NRBMap.put(8517, "Nadwiślański Bank Spółdzielczy w Solcu-Zdroju");
        NRBMap.put(8518, "Bank Spółdzielczy w Starachowicach");
        NRBMap.put(8519, "Bank Spółdzielczy w Stopnicy");
        NRBMap.put(8520, "Bank Spółdzielczy w Suchedniowie");
        NRBMap.put(8521, "Bank Spółdzielczy w Szydłowie");
        NRBMap.put(8523, "Bank Spółdzielczy w Wąchocku");
        NRBMap.put(8525, "Bank Spółdzielczy we Włoszczowie");
        NRBMap.put(8526, "Bank Spółdzielczy w Wodzisławiu");
        NRBMap.put(8530, "Bank Spółdzielczy w Koninie");
        NRBMap.put(8534, "Bank Spółdzielczy w Ślesinie");
        NRBMap.put(8538, "Bank Spółdzielczy w Witkowie");
        NRBMap.put(8539, "Bank Spółdzielczy w Grabowie");
        NRBMap.put(8542, "Bank Spółdzielczy w Słupcy");
        NRBMap.put(8543, "Ludowy Bank Spółdzielczy w Strzałkowie");
        NRBMap.put(8544, "Bank Spółdzielczy w Zagórowie");
        NRBMap.put(8545, "Bank Spółdzielczy w Kłodawie");
        NRBMap.put(8557, "Rejonowy Bank Spółdzielczy w Malanowie");
        NRBMap.put(8558, "Bank Spółdzielczy w Wierzbinku");
        NRBMap.put(8562, "Bank Spółdzielczy w Białogardzie");
        NRBMap.put(8566, "Bałtycki Bank Spółdzielczy");
        NRBMap.put(8570, "Bank Spółdzielczy w Kaliszu Pomorskim");
        NRBMap.put(8577, "Bank Spółdzielczy w Połczynie Zdroju");
        NRBMap.put(8581, "Pomorski Bank Spółdzielczy");
        NRBMap.put(8589, "Bank Spółdzielczy Rzemiosła w Krakowie");
        NRBMap.put(8591, "Krakowski Bank Spółdzielczy");
        NRBMap.put(8597, "Bank Spółdzielczy w Proszowicach");
        NRBMap.put(8600, "Bank Spółdzielczy w Skawinie");
        NRBMap.put(8602, "Bank Spółdzielczy w Dobczycach");
        NRBMap.put(8606, "Bank Spółdzielczy w Raciechowicach");
        NRBMap.put(8612, "Bank Spółdzielczy w Krzeszowicach");
        NRBMap.put(8614, "Bank Spółdzielczy w Słomnikach");
        NRBMap.put(8619, "Małopolski Bank Spółdzielczy");
        NRBMap.put(8621, "Bieszczadzki Bank Spółdzielczy w Ustrzykach Dolnych");
        NRBMap.put(8626, "Bank Spółdzielczy w Kołaczycach");
        NRBMap.put(8627, "Bank Spółdzielczy w Bieczu");
        NRBMap.put(8628, "Bank Spółdzielczy w Lipinkach");
        NRBMap.put(8636, "Bank Spółdzielczy w Rymanowie");
        NRBMap.put(8642, "Podkarpacki Bank Spółdzielczy");
        NRBMap.put(8644, "Bank Spółdzielczy w Chojnowie");
        NRBMap.put(8646, "Bank Spółdzielczy w Głogowie");
        NRBMap.put(8647, "Bank Spółdzielczy w Jaworze");
        NRBMap.put(8649, "Bank Spółdzielczy w Legnicy");
        NRBMap.put(8653, "Bank Spółdzielczy w Przemkowie");
        NRBMap.put(8658, "Powiatowy Bank Spółdzielczy w Złotoryi");
        NRBMap.put(8661, "Bank Spółdzielczy we Włoszakowicach");
        NRBMap.put(8663, "Bank Spółdzielczy w Górze");
        NRBMap.put(8666, "Bank Spółdzielczy w Kościanie");
        NRBMap.put(8667, "Bank Spółdzielczy w Śmiglu");
        NRBMap.put(8669, "Bank Spółdzielczy we Wschowie");
        NRBMap.put(8674, "Bank Spółdzielczy w Jutrosinie");
        NRBMap.put(8678, "Powiatowy Bank Spółdzielczy w Gostyniu");
        NRBMap.put(8682, "Bank Spółdzielczy w Poniecu");
        NRBMap.put(8685, "Rejonowy Bank Spółdzielczy w Bychawie");
        NRBMap.put(8687, "Bank Spółdzielczy w Niedrzwicy Dużej");
        NRBMap.put(8689, "Spółdzielczy Bank Powiatowy w Piaskach");
        NRBMap.put(8693, "Bank Spółdzielczy w Łęcznej");
        NRBMap.put(8702, "Bank Spółdzielczy w Niemcach");
        NRBMap.put(8707, "Bank Spółdzielczy w Lubartowie");
        NRBMap.put(8710, "Bank Spółdzielczy w Niedźwiadzie");
        NRBMap.put(8717, "Bank Spółdzielczy Ziemi Kraśnickiej w Kraśniku");
        NRBMap.put(8721, "Bank Spółdzielczy w Kocku");
        NRBMap.put(8724, "Bank Spółdzielczy w Rykach");
        NRBMap.put(8729, "Bank Spółdzielczy w Józefowie nad Wisłą");
        NRBMap.put(8731, "Bank Spółdzielczy w Kazimierzu Dolnym");
        NRBMap.put(8732, "Bank Spółdzielczy w Kurowie");
        NRBMap.put(8733, "Bank Spółdzielczy w Nałęczowie");
        NRBMap.put(8734, "Powiatowy Bank Spółdzielczy w Opolu Lubelskim");
        NRBMap.put(8735, "Bank Spółdzielczy w Poniatowej");
        NRBMap.put(8736, "Nadwiślański Bank Spółdzielczy w Puławach");
        NRBMap.put(8741, "Bank Spółdzielczy w Końskowoli");
        NRBMap.put(8747, "Bank Spółdzielczy w Czyżewie");
        NRBMap.put(8749, "Bank Spółdzielczy w Ciechanowcu");
        NRBMap.put(8752, "Bank Spółdzielczy w Jedwabnem");
        NRBMap.put(8754, "Bank Spółdzielczy w Kolnie");
        NRBMap.put(8757, "Bank Spółdzielczy w Łomży");
        NRBMap.put(8762, "Hexa Bank Spółdzielczy");
        NRBMap.put(8766, "Bank Spółdzielczy w Sokołach");
        NRBMap.put(8768, "Bank Spółdzielczy w Szczuczynie");
        NRBMap.put(8769, "Spółdzielczy Bank Rozwoju");
        NRBMap.put(8770, "Bank Spółdzielczy w Szumowie");
        NRBMap.put(8774, "Bank Spółdzielczy w Wysokiem Mazowieckiem");
        NRBMap.put(8775, "Bank Spółdzielczy w Zambrowie");
        NRBMap.put(8780, "Bank Spółdzielczy w Aleksandrowie Łódzkim");
        NRBMap.put(8781, "Bank Spółdzielczy w Andrespolu");
        NRBMap.put(8783, "Bank Spółdzielczy w Zgierzu");
        NRBMap.put(8784, "Bank Spółdzielczy Rzemiosła w Łodzi");
        NRBMap.put(8785, "Bank Spółdzielczy w Strykowie");
        NRBMap.put(8786, "Bank Spółdzielczy w Ozorkowie");
        NRBMap.put(8787, "Bank Spółdzielczy w Głownie");
        NRBMap.put(8788, "Bank Spółdzielczy Towarzystwo Oszczędnościowo - Pożyczkowe \"PA-CO-BANK\" w Pabianicach");
        NRBMap.put(8791, "Tatrzański Bank Spółdzielczy");
        NRBMap.put(8792, "Bank Spółdzielczy w Czarnym Dunajcu");
        NRBMap.put(8795, "Bank Spółdzielczy w Gorlicach");
        NRBMap.put(8797, "Bank Spółdzielczy w Grybowie");
        NRBMap.put(8798, "Bank Spółdzielczy w Jabłonce");
        NRBMap.put(8799, "Bank Spółdzielczy w Jordanowie");
        NRBMap.put(8804, "Bank Spółdzielczy w Limanowej");
        NRBMap.put(8805, "Łącki Bank Spółdzielczy");
        NRBMap.put(8808, "Bank Spółdzielczy w Mszanie Dolnej");
        NRBMap.put(8809, "Bank Spółdzielczy Muszyna-Krynica Zdrój");
        NRBMap.put(8811, "Bank Spółdzielczy w Nowym Sączu");
        NRBMap.put(8812, "Bank Spółdzielczy w Nowym Targu");
        NRBMap.put(8813, "Bank Spółdzielczy w Piwnicznej - Zdroju");
        NRBMap.put(8814, "Bank Spółdzielczy w Podegrodziu");
        NRBMap.put(8815, "Bank Spółdzielczy w Rabie Wyżnej");
        NRBMap.put(8816, "Bank Spółdzielczy w Starym Sączu");
        NRBMap.put(8817, "Pieniński Bank Spółdzielczy");
        NRBMap.put(8818, "Bank Spółdzielczy w Łososinie Dolnej");
        NRBMap.put(8821, "Podhalański Bank Spółdzielczy w Zakopanem");
        NRBMap.put(8823, "Bank Spółdzielczy w Olsztynku");
        NRBMap.put(8831, "Bank Spółdzielczy w Iławie");
        NRBMap.put(8832, "Bank Spółdzielczy w Lubawie");
        NRBMap.put(8834, "Bank Spółdzielczy w Nidzicy");
        NRBMap.put(8838, "Bank Spółdzielczy w Szczytnie");
        NRBMap.put(8843, "Morąsko-Zalewski Bank Spółdzielczy");
        NRBMap.put(8848, "Bank Spółdzielczy w Mrągowie");
        NRBMap.put(8851, "Bank Spółdzielczy w Reszlu");
        NRBMap.put(8855, "Bank Spółdzielczy w Bartoszycach");
        NRBMap.put(8857, "Warmiński Bank Spółdzielczy");
        NRBMap.put(8863, "Bank Spółdzielczy w Brzegu");
        NRBMap.put(8866, "Bank Spółdzielczy w Baborowie");
        NRBMap.put(8868, "Bank Spółdzielczy w Głubczycach");
        NRBMap.put(8870, "Bank Spółdzielczy Grodków-Łosiów z siedzibą w Grodkowie");
        NRBMap.put(8872, "Bank Spółdzielczy w Otmuchowie");
        NRBMap.put(8876, "Bank Spółdzielczy w Wołczynie");
        NRBMap.put(8882, "Powiatowy Bank Spółdzielczy w Kędzierzynie-Koźlu");
        NRBMap.put(8883, "Bank Spółdzielczy w Gogolinie");
        NRBMap.put(8884, "Bank Spółdzielczy w Krapkowicach");
        NRBMap.put(8890, "Bank Spółdzielczy w Namysłowie");
        NRBMap.put(8895, "Bank Spółdzielczy w Dobrzeniu Wielkim");
        NRBMap.put(8897, "Bank Spółdzielczy w Łubnianach");
        NRBMap.put(8898, "Bank Spółdzielczy \"Bank Rolników\" w Opolu");
        NRBMap.put(8903, "Bank Spółdzielczy w Białej");
        NRBMap.put(8904, "Bank Spółdzielczy w Głogówku");
        NRBMap.put(8905, "Bank Spółdzielczy w Prudniku");
        NRBMap.put(8907, "Bank Spółdzielczy w Leśnicy");
        NRBMap.put(8909, "Bank Spółdzielczy w Zawadzkiem");
        NRBMap.put(8913, "Limes Bank Spółdzielczy");
        NRBMap.put(8915, "Bank Spółdzielczy w Goworowie");
        NRBMap.put(8916, "Bank Spółdzielczy w Kadzidle");
        NRBMap.put(8917, "Bank Spółdzielczy w Krasnosielcu z siedzibą w Makowie Mazowieckim");
        NRBMap.put(8920, "Kurpiowski Bank Spółdzielczy w Myszyńcu");
        NRBMap.put(8922, "Bank Spółdzielczy w Ostrołęce");
        NRBMap.put(8923, "Bank Spółdzielczy w Ostrowi Mazowieckiej");
        NRBMap.put(8924, "Bank Spółdzielczy w Przasnyszu");
        NRBMap.put(8925, "Bank Spółdzielczy w Różanie");
        NRBMap.put(8930, "Bank Spółdzielczy w Wąsewie");
        NRBMap.put(8931, "Polski Bank Spółdzielczy w Wyszkowie");
        NRBMap.put(8935, "Bank Spółdzielczy w Jastrowiu");
        NRBMap.put(8937, "Nadnotecki Bank Spółdzielczy");
        NRBMap.put(8938, "Bank Spółdzielczy w Łobżenicy");
        NRBMap.put(8940, "Bank Spółdzielczy w Wysokiej");
        NRBMap.put(8941, "Spółdzielczy Bank Ludowy w Złotowie");
        NRBMap.put(8943, "Bank Spółdzielczy w Lipce");
        NRBMap.put(8944, "Spółdzielczy Bank Ludowy w Zakrzewie");
        NRBMap.put(8945, "Bank Spółdzielczy w Chodzieży");
        NRBMap.put(8951, "Bank Spółdzielczy w Czarnkowie");
        NRBMap.put(8959, "Pałucki Bank Spółdzielczy w Wągrowcu");
        NRBMap.put(8960, "Bank Spółdzielczy w Wieleniu");
        NRBMap.put(8961, "Bank Spółdzielczy we Wronkach");
        NRBMap.put(8965, "Bank Spółdzielczy w Bełchatowie");
        NRBMap.put(8973, "Bank Spółdzielczy Ziemi Piotrkowskiej w Piotrkowie Trybunalskim");
        NRBMap.put(8978, "Bank Spółdzielczy w Kleszczowie");
        NRBMap.put(8980, "ESBANK Bank Spółdzielczy");
        NRBMap.put(8985, "Powiatowy Bank Spółdzielczy w Tomaszowie Mazowieckim");
        NRBMap.put(8988, "Bank Spółdzielczy w Przedborzu");
        NRBMap.put(8992, "Bank Spółdzielczy w Opocznie");
        NRBMap.put(9006, "Bank Spółdzielczy w Małej Wsi");
        NRBMap.put(9008, "Bank Spółdzielczy w Staroźrebach");
        NRBMap.put(9010, "Bank Spółdzielczy w Iłowie");
        NRBMap.put(9011, "Vistula Bank Spółdzielczy");
        NRBMap.put(9012, "Bank Spółdzielczy w Gostyninie");
        NRBMap.put(9013, "Bank Spółdzielczy w Gąbinie");
        NRBMap.put(9015, "Sierpecki Bank Spółdzielczy");
        NRBMap.put(9021, "Bank Spółdzielczy \"Wspólna Praca\" w Kutnie");
        NRBMap.put(9022, "Bank Spółdzielczy w Żychlinie");
        NRBMap.put(9023, "Bank Spółdzielczy w Krośniewicach");
        NRBMap.put(9025, "Bank Spółdzielczy w Łaniętach");
        NRBMap.put(9029, "Bank Spółdzielczy Ziemi Łęczyckiej w Łęczycy");
        NRBMap.put(9038, "Bank Spółdzielczy w Starej Białej");
        NRBMap.put(9042, "Bank Spółdzielczy \"MAZOWSZE\" w Płocku");
        NRBMap.put(9043, "POZNAŃSKI BANK SPÓŁDZIELCZY");
        NRBMap.put(9044, "Pobiedzisko - Gośliński Bank Spółdzielczy w Pobiedziskach");
        NRBMap.put(9048, "Gospodarczy Bank Spółdzielczy w Mosinie");
        NRBMap.put(9055, "Ludowy Bank Spółdzielczy w Obornikach");
        NRBMap.put(9058, "Bank Spółdzielczy w Nowym Tomyślu");
        NRBMap.put(9063, "Bank Spółdzielczy w Grodzisku Wielkopolskim");
        NRBMap.put(9065, "Bank Spółdzielczy w Gnieźnie");
        NRBMap.put(9068, "Wielkopolski Bank Spółdzielczy");
        NRBMap.put(9072, "Bank Spółdzielczy Duszniki");
        NRBMap.put(9075, "Bank Spółdzielczy w Kostrzynie");
        NRBMap.put(9076, "Bank Spółdzielczy w Kórniku");
        NRBMap.put(9081, "Nadobrzański Bank Spółdzielczy w Rakoniewicach");
        NRBMap.put(9082, "Bank Spółdzielczy Pojezierza Międzychodzko - Sierakowskiego w Sierakowie");
        NRBMap.put(9084, "Spółdzielczy Bank Ludowy im.Ks.P.Wawrzyniaka");
        NRBMap.put(9085, "BANK SPÓŁDZIELCZY w Środzie Wielkopolskiej");
        NRBMap.put(9091, "Bank Spółdzielczy w Chłopicach");
        NRBMap.put(9093, "Bank Spółdzielczy w Dynowie");
        NRBMap.put(9096, "Bank Spółdzielczy w Jarosławiu");
        NRBMap.put(9101, "Powiatowy Bank Spółdzielczy w Lubaczowie");
        NRBMap.put(9103, "Bank Spółdzielczy w Narolu");
        NRBMap.put(9105, "Bank Spółdzielczy w Pruchniku");
        NRBMap.put(9106, "Bank Spółdzielczy w Przeworsku");
        NRBMap.put(9107, "Bank Spółdzielczy w Radymnie");
        NRBMap.put(9113, "Bank Spółdzielczy w Żurawicy");
        NRBMap.put(9115, "Bank Spółdzielczy Rzemiosła w Radomiu");
        NRBMap.put(9116, "Bank Spółdzielczy im.Stefczyka w Belsku Dużym");
        NRBMap.put(9117, "Bank Spółdzielczy w Białobrzegach");
        NRBMap.put(9121, "Bank Spółdzielczy w Chynowie");
        NRBMap.put(9125, "Bank Spółdzielczy w Głowaczowie");
        NRBMap.put(9128, "Bank Spółdzielczy w Grójcu");
        NRBMap.put(9129, "Bank Spółdzielczy w Iłży");
        NRBMap.put(9130, "Bank Spółdzielczy w Jasieńcu");
        NRBMap.put(9132, "Południowo-Mazowiecki Bank Spółdzielczy w Jedlińsku");
        NRBMap.put(9135, "Bank Spółdzielczy w Lipsku");
        NRBMap.put(9141, "Bank Spółdzielczy w Pionkach");
        NRBMap.put(9145, "Bank Spółdzielczy w Przysusze");
        NRBMap.put(9147, "Bank Spółdzielczy w Radomiu");
        NRBMap.put(9150, "Bank Spółdzielczy w Skaryszewie");
        NRBMap.put(9154, "Bank Spółdzielczy w Warce");
        NRBMap.put(9157, "Bank Spółdzielczy w Zwoleniu");
        NRBMap.put(9158, "Bank Spółdzielczy w Błażowej");
        NRBMap.put(9159, "Bank Spółdzielczy w Głogowie Małopolskim");
        NRBMap.put(9161, "Bank Spółdzielczy w Lubeni");
        NRBMap.put(9162, "Bank Spółdzielczy w Rzeszowie");
        NRBMap.put(9163, "Bank Spółdzielczy w Niechobrzu");
        NRBMap.put(9164, "Bank Spółdzielczy w Tyczynie");
        NRBMap.put(9168, "Bank Spółdzielczy w Strzyżowie");
        NRBMap.put(9170, "Bank Spółdzielczy w Kamieniu");
        NRBMap.put(9171, "Bank Spółdzielczy w Ropczycach");
        NRBMap.put(9172, "Bank Spółdzielczy w Sędziszowie Młp.");
        NRBMap.put(9173, "Bank Spółdzielczy w Wielopolu Skrzyńskim");
        NRBMap.put(9175, "Bank Spółdzielczy w Żołyni");
        NRBMap.put(9176, "EXPRESS BANK SPÓŁDZIELCZY");
        NRBMap.put(9177, "Bank Spółdzielczy w Łańcucie");
        NRBMap.put(9180, "Bank Spółdzielczy w Kolbuszowej");
        NRBMap.put(9182, "Bank Spółdzielczy w Sokołowie Małopolskim");
        NRBMap.put(9183, "Bank Spółdzielczy w Mielcu");
        NRBMap.put(9184, "Bank Spółdzielczy w Przecławiu");
        NRBMap.put(9187, "Bank Spółdzielczy w Leżajsku");
        NRBMap.put(9191, "Bank Spółdzielczy w Jasionce");
        NRBMap.put(9193, "Bank Spółdzielczy w Mokobodach");
        NRBMap.put(9194, "Bank Spółdzielczy w Siedlcach");
        NRBMap.put(9197, "Bank Spółdzielczy w Sobieniach Jeziorach");
        NRBMap.put(9198, "Międzygminny Bank Spółdzielczy w Zbuczynie");
        NRBMap.put(9202, "Bank Spółdzielczy w Adamowie");
        NRBMap.put(9203, "Bank Spółdzielczy w Krzywdzie");
        NRBMap.put(9204, "Bank Spółdzielczy w Łukowie");
        NRBMap.put(9206, "Bank Spółdzielczy w Trzebieszowie");
        NRBMap.put(9210, "Bank Spółdzielczy w Garwolinie");
        NRBMap.put(9217, "Bank Spółdzielczy w Łaskarzewie");
        NRBMap.put(9221, "Powiatowy Bank Spółdzielczy w Sokołowie Podlaskim");
        NRBMap.put(9224, "Bank Spółdzielczy w Kałuszynie");
        NRBMap.put(9226, "Bank Spółdzielczy w Mińsku Mazowieckim");
        NRBMap.put(9227, "Bank Spółdzielczy w Mrozach");
        NRBMap.put(9233, "Bank Spółdzielczy w Łochowie");
        NRBMap.put(9236, "Powiatowy Bank Spółdzielczy w Węgrowie");
        NRBMap.put(9244, "Bank Spółdzielczy Ziemi Wieluńskiej");
        NRBMap.put(9245, "Bank Spółdzielczy w Błaszkach");
        NRBMap.put(9251, "Nadwarciański Bank Spółdzielczy w Działoszynie");
        NRBMap.put(9256, "Rejonowy Bank Spółdzielczy w Lututowie");
        NRBMap.put(9263, "Bank Spółdzielczy w Poddębicach");
        NRBMap.put(9264, "Bank Spółdzielczy w Ruścu");
        NRBMap.put(9267, "Bank Spółdzielczy w Sieradzu");
        NRBMap.put(9269, "Bank Spółdzielczy w Szadku");
        NRBMap.put(9270, "Bank Spółdzielczy w Warcie");
        NRBMap.put(9271, "Bank Spółdzielczy w Wartkowicach");
        NRBMap.put(9279, "Ludowy Bank Spółdzielczy w Zduńskiej Woli");
        NRBMap.put(9283, "Bank Spółdzielczy w Sochaczewie");
        NRBMap.put(9284, "Bank Spółdzielczy w Teresinie");
        NRBMap.put(9288, "Bank Spółdzielczy Ziemi Łowickiej w Łowiczu");
        NRBMap.put(9291, "Bank Spółdzielczy w Białej Rawskiej");
        NRBMap.put(9297, "Bank Spółdzielczy w Skierniewicach");
        NRBMap.put(9302, "Bank Spółdzielczy w Mszczonowie");
        NRBMap.put(9304, "Bank Spółdzielczy w Wiskitkach");
        NRBMap.put(9315, "Bank Spółdzielczy w Ustce");
        NRBMap.put(9317, "Bank Spółdzielczy w Sławnie");
        NRBMap.put(9321, "Bank Spółdzielczy w Bytowie");
        NRBMap.put(9324, "Bank Spółdzielczy w Łebie");
        NRBMap.put(9326, "Bank Spółdzielczy w Człuchowie");
        NRBMap.put(9331, "Bank Spółdzielczy w Ełku");
        NRBMap.put(9334, "Bank Spółdzielczy w Bargłowie Kościelnym");
        NRBMap.put(9339, "Bank Spółdzielczy w Olecku");
        NRBMap.put(9343, "Mazurski Bank Spółdzielczy w Giżycku");
        NRBMap.put(9348, "Bank Spółdzielczy w Węgorzewie");
        NRBMap.put(9350, "Bank Spółdzielczy w Mikołajkach");
        NRBMap.put(9351, "Bank Spółdzielczy w Augustowie");
        NRBMap.put(9354, "Bank Spółdzielczy w Sejnach");
        NRBMap.put(9359, "Bank Spółdzielczy w Suwałkach");
        NRBMap.put(9364, "Warmińsko - Mazurski Bank Spółdzielczy");
        NRBMap.put(9367, "Bank Spółdzielczy w Rutce-Tartak");
        NRBMap.put(9370, "Bank Spółdzielczy w Chojnie");
        NRBMap.put(9371, "Bank Spółdzielczy w Dobrej");
        NRBMap.put(9375, "Bank Spółdzielczy w Goleniowie");
        NRBMap.put(9376, "Bank Spółdzielczy w Gryficach");
        NRBMap.put(9377, "Bank Spółdzielczy w Gryfinie");
        NRBMap.put(9378, "Bank Spółdzielczy w Kamieniu Pomorskim");
        NRBMap.put(9386, "Bank Spółdzielczy w Przybiernowie");
        NRBMap.put(9387, "Pyrzycko-Stargardzki Bank Spółdzielczy");
        NRBMap.put(9388, "Bank Spółdzielczy w Resku");
        NRBMap.put(9393, "Bank Spółdzielczy w Wolinie");
        NRBMap.put(9407, "Bank Spółdzielczy w Grębowie");
        NRBMap.put(9410, "Bank Spółdzielczy w Janowie Lubelskim");
        NRBMap.put(9423, "Bank Spółdzielczy w Ożarowie");
        NRBMap.put(9425, "Bank Spółdzielczy w Połańcu");
        NRBMap.put(9429, "Bank Spółdzielczy w Sandomierzu");
        NRBMap.put(9430, "Nadsański Bank Spółdzielczy");
        NRBMap.put(9431, "Bank Spółdzielczy w Staszowie");
        NRBMap.put(9434, "Bank Spółdzielczy w Tarnobrzegu");
        NRBMap.put(9439, "Bank Spółdzielczy w Zaleszanach");
        NRBMap.put(9453, "Bank Spółdzielczy w Brzesku");
        NRBMap.put(9462, "Bank Spółdzielczy w Dąbrowie Tarnowskiej");
        NRBMap.put(9464, "Bank Spółdzielczy w Szczucinie");
        NRBMap.put(9475, "Bank Spółdzielczy w Dębicy");
        NRBMap.put(9477, "Bank Spółdzielczy w Pilźnie");
        NRBMap.put(9478, "Bank Spółdzielczy w Żyrakowie");
        NRBMap.put(9479, "Bank Spółdzielczy w Radomyślu Wielkim");
        NRBMap.put(9484, "Bank Spółdzielczy w Brodnicy");
        NRBMap.put(9486, "Bank Spółdzielczy w Chełmnie");
        NRBMap.put(9489, "Bank Spółdzielczy w Golubiu - Dobrzyniu");
        NRBMap.put(9491, "Bank Spółdzielczy w Grębocinie");
        NRBMap.put(9496, "Bank Spółdzielczy w Kowalewie Pomorskim");
        NRBMap.put(9500, "Bank Spółdzielczy w Łasinie");
        NRBMap.put(9511, "Bank Spółdzielczy w Toruniu");
        NRBMap.put(9523, "Bank Spółdzielczy w Kłodzku");
        NRBMap.put(9527, "Bank Spółdzielczy w Dzierżoniowie");
        NRBMap.put(9531, "Bank Spółdzielczy w Świdnicy");
        NRBMap.put(9533, "Bank Spółdzielczy w Ząbkowicach Śląskich");
        NRBMap.put(9536, "Gospodarczy Bank Spółdzielczy Radków z/s w Nowej Rudzie");
        NRBMap.put(9537, "Kujawski Bank Spółdzielczy w Aleksandrowie Kujawskim");
        NRBMap.put(9542, "Bank Spółdzielczy w Lipnie");
        NRBMap.put(9546, "Bank Spółdzielczy w Skępem");
        NRBMap.put(9549, "Bank Spółdzielczy w Radziejowie");
        NRBMap.put(9550, "Kujawsko-Dobrzyński Bank Spółdzielczy");
        NRBMap.put(9551, "Bank Spółdzielczy w Piotrkowie Kujawskim");
        NRBMap.put(9557, "Bank Spółdzielczy w Kowalu");
        NRBMap.put(9559, "Bank Spółdzielczy w Lubrańcu");
        NRBMap.put(9574, "Bank Spółdzielczy w Kątach Wrocławskich");
        NRBMap.put(9575, "Bank Spółdzielczy w Kobierzycach");
        NRBMap.put(9582, "Bank Spółdzielczy w Miliczu");
        NRBMap.put(9583, "Bank Spółdzielczy w Obornikach Śląskich");
        NRBMap.put(9584, "Bank Spółdzielczy w Oleśnicy");
        NRBMap.put(9585, "Bank Spółdzielczy w Oławie");
        NRBMap.put(9588, "Gospodarczy Bank Spółdzielczy w Strzelinie");
        NRBMap.put(9589, "Bank Spółdzielczy w Środzie Śląskiej");
        NRBMap.put(9591, "Bank Spółdzielczy w Trzebnicy");
        NRBMap.put(9598, "Bank Spółdzielczy w Żmigrodzie");
        NRBMap.put(9602, "Bank Spółdzielczy w Biłgoraju");
        NRBMap.put(9603, "Bank Spółdzielczy w Dołhobyczowie");
        NRBMap.put(9604, "Bank Spółdzielczy we Frampolu");
        NRBMap.put(9606, "Bank Spółdzielczy w Gorzkowie");
        NRBMap.put(9610, "Bank Spółdzielczy w Izbicy");
        NRBMap.put(9614, "Bank Spółdzielczy w Księżpolu");
        NRBMap.put(9617, "Bank Spółdzielczy w Lubyczy Królewskiej");
        NRBMap.put(9619, "Bank Spółdzielczy w Łukowej");
        NRBMap.put(9620, "Bank Spółdzielczy w Łaszczowie");
        NRBMap.put(9623, "Bank Spółdzielczy w Obszy");
        NRBMap.put(9628, "Bank Spółdzielczy w Nieliszu z/s w Stawie Noakowskim");
        NRBMap.put(9632, "Bank Spółdzielczy w Szczebrzeszynie");
        NRBMap.put(9637, "Bank Spółdzielczy w Tarnogrodzie");
        NRBMap.put(9639, "Bank Spółdzielczy w Tomaszowie Lubelskim");
        NRBMap.put(9642, "Bank Spółdzielczy w Werbkowicach");
        NRBMap.put(9644, "Powiatowy Bank Spółdzielczy w Zamościu");
        NRBMap.put(9649, "Bank Spółdzielczy w Biszczy");
        NRBMap.put(9656, "Bank Spółdzielczy w Krośnie Odrzańskim");
        NRBMap.put(9657, "Bank Spółdzielczy w Żaganiu");
        NRBMap.put(9658, "Bank Spółdzielczy w Iłowej");
        NRBMap.put(9660, "Bank Spółdzielczy w Siedlcu");
        NRBMap.put(9672, "Bank Spółdzielczy w Trzebielu");
        NRBMap.put(9673, "Bank Spółdzielczy w Kożuchowie");
        NRBMap.put(9674, "Bank Spółdzielczy w Nowej Soli");
        NRBMap.put(9681, "Powiatowy Bank Spółdzielczy we Wrześni");


        return NRBMap;


    }

}
